# Generated by Django 4.0 on 2024-11-11 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    
    initial = True  # Indica que es la primera migración para la app
    
    dependencies = [
        # No tiene dependencias, ya que es la primera migración
    ]
    
    operations = [
        migrations.CreateModel(
            name='Article',  # Se crea el modelo 'Article'
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),  # Campo 'id' autogenerado
                ('title', models.CharField(max_length=255)),  # Campo 'title' con longitud máxima de 255 caracteres
                ('content', models.TextField()),  # Campo 'content' para texto largo
            ],
        ),
    ]